export const HOME_PAGE_REQUEST = 'HOME_PAGE_REQUEST';
export const HOME_PAGE_SUCCESS = 'HOME_PAGE_SUCCESS';
export const HOME_PAGE_FAILURE = 'HOME_PAGE_FAILURE';
export const RESET_HOME_PAGE = 'RESET_HOME_PAGE';

